### ISSUE TITLE
Issue with 2022.6

### ISSUE THREAD

**Issue by Alfiegerner** [jonaseickhoff/hass-multiroom-mqtt-mediaplayer#7]
Any one else seeing this:

This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/multiroom-mqtt-mediaplayer/media_player.py:170
Integration: multiroom-mqtt-mediaplayer (documentation)
First occurred: 15:34:48 (1 occurrences)
Last logged: 15:34:48

Unexpected exception importing platform custom_components.multiroom-mqtt-mediaplayer.media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 618, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 635, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/multiroom-mqtt-mediaplayer/media_player.py", line 170, in <module>
    PLATFORM_SCHEMA = mqtt.MQTT_BASE_PLATFORM_SCHEMA.extend(
AttributeError: module 'homeassistant.components.mqtt' has no attribute 'MQTT_BASE_PLATFORM_SCHEMA'

**Comment by jonaseickhoff** [comment]
Hi, please try the updated version 1.0.2
